### ISSUE TITLE
Java.lang.IllegalArgumentException: A classpath element should either be a jar or a folder

### ISSUE THREAD

**Issue by mboussaa** [STAMP-project/evosuite-model-seeding-empirical-evaluation#11]
Steps to reproduce:
> ./compileSF110.sh

> . main.sh -m 2 classes.csv 2 180 100 0.5

Classes.csv

> org.javathena.core.utiles.Functions,81_javathena

Error:

```
[MASTER] 16:45:17.810 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1570805117805. Configuration id : null
java.lang.IllegalArgumentException: A classpath element should either be a jar or a folder: bins/81_javathena/build.xml
	at org.evosuite.classpath.ClassPathHandler.checkIfValidClasspathEntry(ClassPathHandler.java:214) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.classpath.ClassPathHandler.getClassPath(ClassPathHandler.java:118) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.classpath.ClassPathHandler.changeTargetClassPath(ClassPathHandler.java:105) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.CommandLineParameters.handleClassPath(CommandLineParameters.java:232) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:222) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.main(EvoSuite.java:341) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]

```

**Comment by mboussaa** [comment]
Found the solution. Path was wrong
